package message

type QTYPE uint16

const (
	QTYPE_A     QTYPE = 1
	QTYPE_NS    QTYPE = 2
	QTYPE_MD    QTYPE = 3
	QTYPE_MF    QTYPE = 4
	QTYPE_CNAME QTYPE = 5
	QTYPE_SOA   QTYPE = 6
	QTYPE_MB    QTYPE = 7
	QTYPE_MG    QTYPE = 8
	QTYPE_MR    QTYPE = 9
	QTYPE_NULL  QTYPE = 10
	QTYPE_WKS   QTYPE = 11
	QTYPE_PTR   QTYPE = 12
	QTYPE_HINFO QTYPE = 13
	QTYPE_MINFO QTYPE = 14
	QTYPE_MX    QTYPE = 15
	QTYPE_TXT   QTYPE = 16
	QTYPE_AXFR  QTYPE = 252
	QTYPE_MAILB QTYPE = 253
	QTYPE_MAILA QTYPE = 254
	QTYPE_ALL   QTYPE = 255
)

type QCLASS uint16

const (
	QCLASS_IN  QCLASS = 1
	QCLASS_CS  QCLASS = 2
	QCLASS_CH  QCLASS = 3
	QCLASS_HS  QCLASS = 4
	QCLASS_ANY QCLASS = 255
)

type Question struct {
	QName  []byte
	QType  QTYPE
	QClass QCLASS
}
